#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Daniel Polo
"""Regenerate the session-journal index from the checkpoints on disk (roadmap 5.32).

    python tools/update_journal_index.py [--check]

`docs/journal/README.md` listed 69 checkpoints on 2026-09-13 and `docs/journal/2026/**`
held 104: writing the index by hand — step 2 of the three-step close AGENTS.md §7 and
this file's own preamble describe — had silently stopped three days and twenty-four
sessions earlier, beginning with roadmap 5.1's (roadmap 5.32, found while adding a row
at 5.26). Nothing caught it, because nothing read the two against each other.

The index was never carrying information the tree did not already hold. Every
checkpoint's own first line is `# <date> — <title>`, one write ahead of the row the
index wants for it, so hand-copying it was always a chance to drift and never a chance
to add anything the file did not already say. That is what makes generation the answer
rather than a stronger lint: a hand-written copy of a fact the tree already states is
the defect, and `tools/consistency_lint.py`'s `journal-index` check (roadmap 5.32) holds
this file to what a fresh run of this script would produce, the same way
`build_ingested_cases.py --check` holds its own output — a generated file that no
longer matches its generator is what the check exists to catch, not a reason to fix it
quietly.

Newest first is the only ordering the tree can support without inventing one: nothing on
disk says which of two sessions opened on the same date happened first, so entries
sharing a date sort by filename, descending — the same rule a clean checkout applies
unasked. The preamble above `## Index` is the only part of this file a person still
writes; everything from that heading down is this script's output.
"""

import calendar
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JOURNAL = ROOT / "docs" / "journal"
INDEX = JOURNAL / "README.md"
MARKER = "## Index"

TITLE = re.compile(r"^# (\d{4}-\d{2}-\d{2}) — (.+)$")


def checkpoints() -> list[tuple[str, str, str]]:
    """Every `(relative path, date, title)`, one per checkpoint file on disk.

    Reads only the first line of each file — the checkpoint's own H1 — and
    refuses one that does not carry the date the workflow requires, or whose
    filename disagrees with it: a heading this script cannot read is a
    checkpoint the index cannot state either.
    """
    found: list[tuple[str, str, str]] = []
    for path in sorted(JOURNAL.glob("*/*/*.md")):
        relative = path.relative_to(JOURNAL).as_posix()
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
        match = TITLE.match(first_line)
        if match is None:
            msg = f"{relative}: first line is not '# <date> — <title>' ({first_line!r})"
            raise SystemExit(msg)
        date, title = match.groups()
        if not path.name.startswith(date):
            msg = f"{relative}: its own heading names a different date ({date})"
            raise SystemExit(msg)
        found.append((relative, date, title))
    return found


def render(entries: list[tuple[str, str, str]]) -> str:
    """The `## Index` section, generated whole from `entries`."""
    by_year: dict[str, dict[str, list[tuple[str, str, str]]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for relative, date, title in entries:
        by_year[date[:4]][date[5:7]].append((relative, date, title))

    lines = [
        MARKER,
        "",
        "_(newest first, generated by `tools/update_journal_index.py` — do not edit by hand)_",
        "",
    ]
    for year in sorted(by_year, reverse=True):
        lines.append(f"### {year}")
        lines.append("")
        months = by_year[year]
        for month in sorted(months, reverse=True):
            lines.append(f"#### {calendar.month_name[int(month)]}")
            lines.append("")
            for relative, date, title in sorted(months[month], reverse=True):
                lines.append(f"- [{date} — {title}]({relative})")
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    entries = checkpoints()
    current = INDEX.read_text(encoding="utf-8")
    marker_at = current.find(MARKER)
    if marker_at == -1:
        raise SystemExit(f"{INDEX}: no '{MARKER}' heading to anchor the generated section")
    updated = current[:marker_at] + render(entries)

    if check_only:
        if updated != current:
            print("docs/journal/README.md is stale; run `python tools/update_journal_index.py`")
            return 1
        print(f"journal index current: {len(entries)} checkpoint(s)")
        return 0

    if updated == current:
        print(f"journal index unchanged: {len(entries)} checkpoint(s)")
        return 0
    INDEX.write_text(updated, encoding="utf-8", newline="\n")
    print(f"journal index updated: {len(entries)} checkpoint(s)")
    print("Review the diff — it reflects checkpoints already on disk.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
